[workspace]
resolver = "2"
members = [
	"rust",
	"rust/lib"
]

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.73.0"

[workspace.dependencies]
ahash = "0.8.6"
hashbrown = "0.14.2"
